# Databricks notebook source
# MAGIC %md
# MAGIC # 03 — Train the ensemble model
# MAGIC
# MAGIC **Architecture (Fourth-good-model port):**
# MAGIC - **Stage 1** — binary LightGBM classifier predicts `P(quantite = 0)`.
# MAGIC   Optionally isotonic-calibrated on validation so the output probability
# MAGIC   is monotone in the true zero rate.
# MAGIC - **Stage 2a** — LightGBM Tweedie regressor on raw `quantite`, trained
# MAGIC   on every row (including zeros) with sample weights proportional to
# MAGIC   the magnitude (WAPE-aligned).
# MAGIC - **Stage 2b** — XGBoost Tweedie regressor with the same setup. Only
# MAGIC   purpose: ensemble diversity — LGB and XGB have different split
# MAGIC   strategies and categorical handling, so their errors decorrelate.
# MAGIC - **Stacker** — `sklearn.linear_model.Ridge(positive=True,
# MAGIC   fit_intercept=False)` blends five signals: `lgb_pred`, `xgb_pred`,
# MAGIC   `lag_52`, `pair_mean`, `pair_median`. Fitted on **out-of-fold**
# MAGIC   predictions generated by `TimeSeriesSplit` on the training set so the
# MAGIC   stacker cannot overfit validation. Falls back to a val-fit if
# MAGIC   `STACKING_OOF_FOLDS < 2`.
# MAGIC - **Adaptive threshold** — `thr = clip(base - slope * zero_rate, lo, hi)`,
# MAGIC   swept on a small (base, slope) grid against val WAPE.
# MAGIC - **Hard dead-pair override** — `is_dead_pair == 1 → 0`.
# MAGIC - **Multi-seed** — each stage can train k models (config-driven) and
# MAGIC   averages predictions before stacking.
# MAGIC
# MAGIC **No hyperparameter tuning is performed.** Every knob comes from
# MAGIC `00_config.py` and is either fixed or selected by a tiny grid sweep.
# MAGIC
# MAGIC **Inputs:** `gold_train`, `gold_validation`, `gold_internal_test`.
# MAGIC **Outputs:**
# MAGIC - All models, the stacker, the calibrator, and a `manifest.json` written
# MAGIC   under the MLflow artifact path `MLFLOW_ENSEMBLE_ARTIFACT_PATH`.
# MAGIC - Validation + internal-test predictions as Delta tables, including a
# MAGIC   per-row `threshold` column so downstream notebooks can reproduce the
# MAGIC   decision rule without looking up parameters in MLflow.

# COMMAND ----------

# MAGIC %run ./00_config

# COMMAND ----------

# MAGIC %pip install lightgbm==4.3.0 xgboost==2.0.3
# MAGIC dbutils.library.restartPython()

# COMMAND ----------

# MAGIC %run ./00_config

# COMMAND ----------

import sys
sys.path.append("./")

import gc
import json
import os
import pickle
import tempfile

import numpy as np
import pandas as pd
import lightgbm as lgb
import xgboost as xgb
import mlflow
from sklearn.linear_model import Ridge
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import TimeSeriesSplit
from pyspark.sql.types import (
    DoubleType,
    LongType,
    StringType,
    StructField,
    StructType,
)

from src.utils import (
    apply_non_iterative_feature_fallbacks,
    wape_numpy,
    wape_lgb_feval,
)

# COMMAND ----------

mlflow.set_experiment(MLFLOW_EXPERIMENT)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Load the pre-split feature tables from the Lakeflow pipeline

# COMMAND ----------

cols_needed = (
    ["semaine", "code_agence", "code_article", "week_id", "quantite", "is_dead_pair"]
    + FEATURES
)

train_sdf = spark.table(TBL_GOLD_TRAIN).select(*cols_needed)
val_sdf   = spark.table(TBL_GOLD_VAL).select(*cols_needed)
test_sdf  = spark.table(TBL_GOLD_INTERNAL_TEST).select(*cols_needed)

train_pd = train_sdf.toPandas()
val_pd   = val_sdf.toPandas()
test_pd  = test_sdf.toPandas()

print(f"Train: {len(train_pd):,}   Val: {len(val_pd):,}   Internal test: {len(test_pd):,}")

# Double-check the split has no overlap.
assert train_pd["week_id"].max() < val_pd["week_id"].min(), "Temporal split broken"
assert val_pd["week_id"].max() < test_pd["week_id"].min(), "Temporal split broken"

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Prepare X / y / is_zero

# COMMAND ----------

def build_xy(df: pd.DataFrame, use_non_iterative_fallbacks: bool = False):
    X = df[FEATURES].copy()
    if use_non_iterative_fallbacks:
        X = apply_non_iterative_feature_fallbacks(X, FEATURES)
    for c in FEATURES_CATEGORICAL:
        if c in X.columns:
            X[c] = X[c].astype("category")
    y = df["quantite"].astype(float).values
    is_zero = (y == 0).astype(int)
    return X, y, is_zero


X_tr, y_tr, z_tr = build_xy(train_pd)
X_va, y_va, z_va = build_xy(val_pd, use_non_iterative_fallbacks=True)
X_te, y_te, z_te = build_xy(test_pd, use_non_iterative_fallbacks=True)

print(f"Zero rate train: {z_tr.mean():.3f}   val: {z_va.mean():.3f}   test: {z_te.mean():.3f}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Helpers — individual trainers, predictors, baselines

# COMMAND ----------

def train_lgb_classifier(X_tr_, z_tr_, X_va_, z_va_, seed: int):
    params = dict(LGB_PARAMS_ZERO)
    params["seed"] = seed
    dtr = lgb.Dataset(
        X_tr_, label=z_tr_,
        categorical_feature=FEATURES_CATEGORICAL,
        free_raw_data=False,
    )
    dva = lgb.Dataset(
        X_va_, label=z_va_,
        reference=dtr,
        categorical_feature=FEATURES_CATEGORICAL,
        free_raw_data=False,
    )
    return lgb.train(
        params, dtr,
        num_boost_round=LGB_NUM_ROUNDS_ZERO,
        valid_sets=[dva], valid_names=["val"],
        callbacks=[
            lgb.early_stopping(LGB_EARLY_STOP_ZERO, first_metric_only=True),
            lgb.log_evaluation(period=200),
        ],
    )


def train_lgb_regressor(X_tr_, y_tr_, X_va_, y_va_, seed: int):
    # NOTE: no sample_weight. Tweedie already has an implicit heteroskedastic
    # weighting (variance ∝ μ^p), so multiplying the loss by y double-counts
    # high-volume rows and pushes the fit to over-predict. Stick to plain
    # Tweedie — this matches the Fourth-good-model notebook.
    params = dict(LGB_PARAMS_QTY)
    params["seed"] = seed
    params["metric"] = "None"  # feval below is authoritative
    dtr = lgb.Dataset(
        X_tr_, label=y_tr_,
        categorical_feature=FEATURES_CATEGORICAL,
        free_raw_data=False,
    )
    dva = lgb.Dataset(
        X_va_, label=y_va_,
        reference=dtr,
        categorical_feature=FEATURES_CATEGORICAL,
        free_raw_data=False,
    )
    return lgb.train(
        params, dtr,
        num_boost_round=LGB_NUM_ROUNDS_QTY,
        valid_sets=[dva], valid_names=["val"],
        feval=wape_lgb_feval,
        callbacks=[
            lgb.early_stopping(LGB_EARLY_STOP_QTY, first_metric_only=True),
            lgb.log_evaluation(period=200),
        ],
    )


def train_xgb_regressor(X_tr_, y_tr_, X_va_, y_va_, seed: int):
    # Same rationale as train_lgb_regressor: no sample_weight on Tweedie.
    params = dict(XGB_PARAMS_QTY)
    params["seed"] = seed
    dtr = xgb.DMatrix(X_tr_, label=y_tr_, enable_categorical=True)
    dva = xgb.DMatrix(X_va_, label=y_va_, enable_categorical=True)
    return xgb.train(
        params, dtr,
        num_boost_round=XGB_NUM_ROUNDS_QTY,
        evals=[(dva, "val")],
        early_stopping_rounds=XGB_EARLY_STOP_QTY,
        verbose_eval=200,
    )


def predict_lgb(m, X) -> np.ndarray:
    return np.clip(m.predict(X, num_iteration=m.best_iteration), 0.0, None)


def predict_xgb(m, X) -> np.ndarray:
    dm = xgb.DMatrix(X, enable_categorical=True)
    return np.clip(m.predict(dm, iteration_range=(0, m.best_iteration + 1)), 0.0, None)


def baseline_matrix(df: pd.DataFrame) -> np.ndarray:
    """(N, k) matrix of baseline columns used by the Ridge stacker.

    `lag_52`, `pair_mean`, `pair_median` are already materialised in the
    gold feature table, so we don't recompute them — we just stack and
    zero-fill NaNs so Ridge stays happy.
    """
    cols = [np.nan_to_num(df[c].values.astype(float), nan=0.0) for c in STACK_BASELINE_COLS]
    return np.column_stack(cols)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Train the three-model ensemble on (train, val)

# COMMAND ----------

with mlflow.start_run(run_name="train_pipeline") as parent_run:
    mlflow.log_params({
        "n_features":          len(FEATURES),
        "train_rows":          len(train_pd),
        "val_rows":            len(val_pd),
        "internal_test_rows":  len(test_pd),
        "train_end":           TRAIN_END_WEEK_ID,
        "val_end":             VAL_END_WEEK_ID,
        "internal_test_start": INTERNAL_TEST_START_WEEK_ID,
        "internal_test_end":   INTERNAL_TEST_END_WEEK_ID,
        "ensemble_seeds":      json.dumps(ENSEMBLE_SEEDS),
        "stacking_oof_folds":  STACKING_OOF_FOLDS,
        "calibrate_zero_clf":  CALIBRATE_ZERO_CLF,
        "dead_pair_force_zero": DEAD_PAIR_FORCE_ZERO,
    })

    # ──────────────────────── Stage 1 — zero classifier ────────────────────
    print("=" * 60)
    print("STAGE 1 — LightGBM zero classifier")
    print("=" * 60)

    clf_models = []
    clf_val_probs = []
    for seed in ENSEMBLE_SEEDS:
        print(f"  seed={seed}")
        m = train_lgb_classifier(X_tr, z_tr, X_va, z_va, seed)
        clf_models.append(m)
        clf_val_probs.append(m.predict(X_va, num_iteration=m.best_iteration))
    p_zero_val_raw = np.mean(np.stack(clf_val_probs, axis=0), axis=0)

    # Isotonic calibration (optional) — fit on val (clf, target=is_zero).
    if CALIBRATE_ZERO_CLF:
        calibrator = IsotonicRegression(out_of_bounds="clip", y_min=0.0, y_max=1.0)
        calibrator.fit(p_zero_val_raw, z_va)
        p_zero_val = calibrator.transform(p_zero_val_raw)
        print("  → isotonic calibration fitted")
    else:
        calibrator = None
        p_zero_val = p_zero_val_raw

    val_logloss = float(
        -np.mean(
            z_va * np.log(np.clip(p_zero_val, 1e-7, 1 - 1e-7))
            + (1 - z_va) * np.log(np.clip(1 - p_zero_val, 1e-7, 1 - 1e-7))
        )
    )
    mlflow.log_metric("val_logloss_clf", val_logloss)

    # ─────────────────── Stage 2a — LightGBM Tweedie regressor ─────────────
    print("=" * 60)
    print("STAGE 2a — LightGBM Tweedie regressor")
    print("=" * 60)

    lgb_reg_models = []
    lgb_reg_val_preds = []
    for seed in ENSEMBLE_SEEDS:
        print(f"  seed={seed}")
        m = train_lgb_regressor(X_tr, y_tr, X_va, y_va, seed)
        lgb_reg_models.append(m)
        lgb_reg_val_preds.append(predict_lgb(m, X_va))
    lgb_val_avg = np.mean(np.stack(lgb_reg_val_preds, axis=0), axis=0)
    mlflow.log_metric("val_wape_lgb_only", wape_numpy(y_va, lgb_val_avg))

    # ─────────────────── Stage 2b — XGBoost Tweedie regressor ──────────────
    print("=" * 60)
    print("STAGE 2b — XGBoost Tweedie regressor")
    print("=" * 60)

    xgb_reg_models = []
    xgb_reg_val_preds = []
    for seed in ENSEMBLE_SEEDS:
        print(f"  seed={seed}")
        m = train_xgb_regressor(X_tr, y_tr, X_va, y_va, seed)
        xgb_reg_models.append(m)
        xgb_reg_val_preds.append(predict_xgb(m, X_va))
    xgb_val_avg = np.mean(np.stack(xgb_reg_val_preds, axis=0), axis=0)
    mlflow.log_metric("val_wape_xgb_only", wape_numpy(y_va, xgb_val_avg))

    # ─────────────────────────── Stacker (Ridge) ───────────────────────────
    print("=" * 60)
    print("STACKER — Ridge(positive=True, fit_intercept=False)")
    print("=" * 60)

    stacker = Ridge(alpha=STACKING_RIDGE_ALPHA, positive=True, fit_intercept=False)

    if STACKING_OOF_FOLDS >= 2:
        # TimeSeriesSplit on train sorted by week_id. Only the first seed is
        # used for OOF (adding more seeds here is redundant with averaging).
        print(f"  Fitting OOF stacker with {STACKING_OOF_FOLDS} folds (first seed only)...")
        order = np.argsort(train_pd["week_id"].values, kind="stable")
        inv_order = np.empty_like(order)
        inv_order[order] = np.arange(len(order))

        X_tr_sorted = X_tr.iloc[order].reset_index(drop=True)
        y_tr_sorted = y_tr[order]

        oof_lgb_s = np.full(len(X_tr_sorted), np.nan, dtype=float)
        oof_xgb_s = np.full(len(X_tr_sorted), np.nan, dtype=float)

        tscv = TimeSeriesSplit(n_splits=STACKING_OOF_FOLDS)
        first_seed = ENSEMBLE_SEEDS[0]
        for fold_ix, (tr_idx, va_idx) in enumerate(tscv.split(X_tr_sorted)):
            print(f"   fold {fold_ix + 1}/{STACKING_OOF_FOLDS}")
            Xf_tr = X_tr_sorted.iloc[tr_idx]
            yf_tr = y_tr_sorted[tr_idx]
            Xf_va = X_tr_sorted.iloc[va_idx]
            yf_va = y_tr_sorted[va_idx]

            m_lgb_f = train_lgb_regressor(Xf_tr, yf_tr, Xf_va, yf_va, first_seed)
            oof_lgb_s[va_idx] = predict_lgb(m_lgb_f, Xf_va)
            del m_lgb_f; gc.collect()

            m_xgb_f = train_xgb_regressor(Xf_tr, yf_tr, Xf_va, yf_va, first_seed)
            oof_xgb_s[va_idx] = predict_xgb(m_xgb_f, Xf_va)
            del m_xgb_f; gc.collect()

        # Invert the sort so the OOF arrays match the original train order.
        oof_lgb = oof_lgb_s[inv_order]
        oof_xgb = oof_xgb_s[inv_order]
        oof_mask = ~np.isnan(oof_lgb)

        bl_tr = baseline_matrix(train_pd)
        stack_fit_X = np.column_stack([
            oof_lgb[oof_mask],
            oof_xgb[oof_mask],
            bl_tr[oof_mask],
        ])
        stack_fit_y = y_tr[oof_mask]
        stacker.fit(stack_fit_X, stack_fit_y)
        stack_fit_source = f"oof_train (n={oof_mask.sum()}/{len(y_tr)})"
    else:
        print("  Fitting Ridge on validation predictions (STACKING_OOF_FOLDS < 2)")
        bl_va_fit = baseline_matrix(val_pd)
        stack_fit_X = np.column_stack([lgb_val_avg, xgb_val_avg, bl_va_fit])
        stacker.fit(stack_fit_X, y_va)
        stack_fit_source = "val_predictions"

    coef = stacker.coef_
    stack_feature_names = ["lgb", "xgb"] + STACK_BASELINE_COLS
    print("  Ridge weights:")
    for name, w in zip(stack_feature_names, coef):
        print(f"    {name:<12s} = {w: .4f}")
    mlflow.log_params({f"ridge_w_{n}": float(w) for n, w in zip(stack_feature_names, coef)})
    mlflow.log_param("stack_fit_source", stack_fit_source)

    # ─────────────── Apply the stacker on val, then adaptive threshold ─────
    bl_va = baseline_matrix(val_pd)
    stack_va = np.column_stack([lgb_val_avg, xgb_val_avg, bl_va])
    blend_val_raw = np.clip(stacker.predict(stack_va), 0.0, None)

    # Adaptive (base, slope) grid sweep on the calibrated zero proba.
    zero_rate_val = np.nan_to_num(val_pd[ZERO_RATE_FEATURE].values.astype(float), nan=0.0)
    is_dead_val = val_pd["is_dead_pair"].values.astype(int)

    best_base, best_slope, best_wape = None, None, float("inf")
    sweep_rows = []
    for base in ADAPTIVE_THRESHOLD_BASE_GRID:
        for slope in ADAPTIVE_THRESHOLD_SLOPE_GRID:
            thr = np.clip(
                base - slope * zero_rate_val,
                ADAPTIVE_THRESHOLD_CLIP[0],
                ADAPTIVE_THRESHOLD_CLIP[1],
            )
            is_zero_pred = p_zero_val > thr
            final_val = np.where(is_zero_pred, 0.0, blend_val_raw)
            if DEAD_PAIR_FORCE_ZERO:
                final_val = np.where(is_dead_val == 1, 0.0, final_val)
            w = wape_numpy(y_va, final_val)
            sweep_rows.append({"base": base, "slope": slope, "wape": w})
            if w < best_wape:
                best_base, best_slope, best_wape = base, slope, w

    sweep_df = pd.DataFrame(sweep_rows).sort_values("wape")
    print(sweep_df.head(8).to_string(index=False))
    print(f"  → best base={best_base}, slope={best_slope}, WAPE={best_wape:.4f}")

    mlflow.log_params({
        "adaptive_base":  float(best_base),
        "adaptive_slope": float(best_slope),
    })
    mlflow.log_metric("val_wape_model", float(best_wape))
    sweep_df.to_csv("/tmp/threshold_sweep.csv", index=False)
    mlflow.log_artifact("/tmp/threshold_sweep.csv")

    # Final val prediction column with the chosen (base, slope).
    effective_thr_val = np.clip(
        best_base - best_slope * zero_rate_val,
        ADAPTIVE_THRESHOLD_CLIP[0],
        ADAPTIVE_THRESHOLD_CLIP[1],
    )
    val_final = np.where(p_zero_val > effective_thr_val, 0.0, blend_val_raw)
    if DEAD_PAIR_FORCE_ZERO:
        val_final = np.where(is_dead_val == 1, 0.0, val_final)

    # ───────── Score the labelled internal test set (same pipeline, once) ──
    clf_probs_te = np.mean(
        np.stack([m.predict(X_te, num_iteration=m.best_iteration) for m in clf_models], axis=0),
        axis=0,
    )
    p_zero_te = calibrator.transform(clf_probs_te) if calibrator is not None else clf_probs_te

    lgb_te_avg = np.mean(np.stack([predict_lgb(m, X_te) for m in lgb_reg_models], axis=0), axis=0)
    xgb_te_avg = np.mean(np.stack([predict_xgb(m, X_te) for m in xgb_reg_models], axis=0), axis=0)

    bl_te = baseline_matrix(test_pd)
    blend_te_raw = np.clip(
        stacker.predict(np.column_stack([lgb_te_avg, xgb_te_avg, bl_te])),
        0.0, None,
    )

    zero_rate_te = np.nan_to_num(test_pd[ZERO_RATE_FEATURE].values.astype(float), nan=0.0)
    is_dead_te = test_pd["is_dead_pair"].values.astype(int)
    thr_te = np.clip(
        best_base - best_slope * zero_rate_te,
        ADAPTIVE_THRESHOLD_CLIP[0],
        ADAPTIVE_THRESHOLD_CLIP[1],
    )
    test_final = np.where(p_zero_te > thr_te, 0.0, blend_te_raw)
    if DEAD_PAIR_FORCE_ZERO:
        test_final = np.where(is_dead_te == 1, 0.0, test_final)

    internal_test_wape = wape_numpy(y_te, test_final)
    mlflow.log_metric("internal_test_wape", float(internal_test_wape))
    print(f"  internal test WAPE = {internal_test_wape:.4f}")

    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## 5. Persist models + stacker + calibrator as MLflow artifacts

    # COMMAND ----------

    tmpdir = tempfile.mkdtemp(prefix="ensemble_")
    # LGB boosters → text format (portable, fast to reload via lgb.Booster).
    for seed, m in zip(ENSEMBLE_SEEDS, clf_models):
        m.save_model(os.path.join(tmpdir, f"clf_lgb_seed{seed}.txt"))
    for seed, m in zip(ENSEMBLE_SEEDS, lgb_reg_models):
        m.save_model(os.path.join(tmpdir, f"reg_lgb_seed{seed}.txt"))
    # XGB boosters → UBJ (binary, compact).
    for seed, m in zip(ENSEMBLE_SEEDS, xgb_reg_models):
        m.save_model(os.path.join(tmpdir, f"reg_xgb_seed{seed}.ubj"))

    with open(os.path.join(tmpdir, "stacker.pkl"), "wb") as f:
        pickle.dump(stacker, f)
    if calibrator is not None:
        with open(os.path.join(tmpdir, "calibrator.pkl"), "wb") as f:
            pickle.dump(calibrator, f)

    manifest = {
        "ensemble_seeds":        ENSEMBLE_SEEDS,
        "clf_best_iter":         [int(m.best_iteration) for m in clf_models],
        "lgb_reg_best_iter":     [int(m.best_iteration) for m in lgb_reg_models],
        "xgb_reg_best_iter":     [int(m.best_iteration) for m in xgb_reg_models],
        "calibrate_zero_clf":    CALIBRATE_ZERO_CLF,
        "stacker_features":      stack_feature_names,
        "stacker_coef":          coef.tolist(),
        "stack_baseline_cols":   STACK_BASELINE_COLS,
        "adaptive_base":         float(best_base),
        "adaptive_slope":        float(best_slope),
        "adaptive_clip":         list(ADAPTIVE_THRESHOLD_CLIP),
        "zero_rate_feature":     ZERO_RATE_FEATURE,
        "dead_pair_force_zero":  DEAD_PAIR_FORCE_ZERO,
        "features":              FEATURES,
        "features_categorical":  FEATURES_CATEGORICAL,
        "val_wape":              float(best_wape),
        "internal_test_wape":    float(internal_test_wape),
    }
    with open(os.path.join(tmpdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    mlflow.log_artifacts(tmpdir, artifact_path=MLFLOW_ENSEMBLE_ARTIFACT_PATH)
    print(f"  Ensemble artifacts logged under '{MLFLOW_ENSEMBLE_ARTIFACT_PATH}/'")

    # COMMAND ----------

    # MAGIC %md
    # MAGIC ## 6. Write validation + internal test predictions to Delta

    # COMMAND ----------

    # Schema extended with `threshold` so 04_evaluate / 05_inference can
    # reproduce the decision rule row by row, without looking up params.
    schema = StructType([
        StructField("semaine",      StringType()),
        StructField("code_agence",  LongType()),
        StructField("code_article", LongType()),
        StructField("quantite",     LongType()),
        StructField("p_zero",       DoubleType()),
        StructField("qty_pred",     DoubleType()),
        StructField("prediction",   DoubleType()),
        StructField("threshold",    DoubleType()),
    ])

    val_out = val_pd[["semaine", "code_agence", "code_article", "quantite"]].copy()
    val_out["p_zero"]     = p_zero_val
    val_out["qty_pred"]   = blend_val_raw
    val_out["prediction"] = val_final
    val_out["threshold"]  = effective_thr_val
    (
        spark.createDataFrame(val_out, schema=schema).write
        .format("delta").mode("overwrite").option("overwriteSchema", "true")
        .saveAsTable(TBL_VAL_PREDICTIONS)
    )
    print(f"  Wrote validation predictions to {TBL_VAL_PREDICTIONS}")

    test_out = test_pd[["semaine", "code_agence", "code_article", "quantite"]].copy()
    test_out["p_zero"]     = p_zero_te
    test_out["qty_pred"]   = blend_te_raw
    test_out["prediction"] = test_final
    test_out["threshold"]  = thr_te
    (
        spark.createDataFrame(test_out, schema=schema).write
        .format("delta").mode("overwrite").option("overwriteSchema", "true")
        .saveAsTable(TBL_INTERNAL_TEST_PREDICTIONS)
    )
    print(
        f"  Wrote internal test predictions to {TBL_INTERNAL_TEST_PREDICTIONS} "
        f"(WAPE={internal_test_wape:.4f})"
    )
